name: 'nginx module build'
description: 'bulid nginx modules using a specified nginx version'
author: 'Johannes Westhuis'
branding:
  icon: 'octagon'
  color: 'green'
inputs:
  nginx-version:
    description: 'tag or commit id of nginx repo - if omitted, the current master will be used'
  additional-packages:
    description: 'packages that need to be installed to compile the module successfully'
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.nginx-version }}
    - ${{ inputs.additional-packages }}
